at2com_media:
    resource: "@At2comMediaBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
